{% set name = "dtool_symlink" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-symlink/dtool-symlink-{{ version }}.tar.gz
  sha256: "b8efec1d72dc56cb3825d1e237316bf6d926c775c005ff2179ed8ff2cedad248"

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli

test:
  imports:
    - dtool_symlink
    - dtool_symlink.storagebroker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-symlink
  license: MIT
  license_file: LICENSE.rst
  summary: 'give dtool ability to create dataset where data directory is a symlink.'
  doc_url: https://github.com/jic-dtool/dtool-symlink
  dev_url: https://github.com/jic-dtool/dtool-symlink

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
