travis:
  secure:
    BINSTAR_TOKEN: g06hRMAIey9i8UW/zwQC1RNJvDakpZff8QrRkyh9bkSAkjXK3xM99Hx4H8uuYBarQxW+xEKwFCfwpY9CuF19mRxOz5NcyHZtxSHi7BFZGWmrGN7Adaazu35vE2GPXBoHWOv7jvKu8kcboAjBxcT2DjIMKPqP7h4FNsQCRk1fbR4SEp7x/WnTfmWL7kanTc7OzUDKzQoBQWU/sgycOAz3uRhI7OMRw78/VmEU6+GEV6kdtoQGLGs2DR0BYu/yfdtWoGmQU9+WQ97C8HqV8sAcmw0RVDbTvZagOj4lk5yQdPhmJ3mltFYFa5k3dKXMSfd8N+l60P1/wfYkrcbZIbKxYCkjv7RzY+SVfIVSVzwa66vw7Afam8dfcWds1xDgTCxViu42XQctYzwrU5DE+SqVMinL7YQGCG1M3Q3E0/gJcN48awHNmAocxBjdkrfMcKM6+HfNPaOFW5q57FK1O7Mfx/ykK5bVpH1H34vl0TD/CwDm8hLAqQkHOSZVmT2Zt7UmN1lNKiSX8ovLvPeTiPdtlO1ja2nfuArFLBzFxeJ8H9fVyDtcPR66vWT7kLIx+r4ZKptdNbGjccIMTinWERKf7KcDWaZFUaCo2f6SzktTruyuiXmD6gttZ9MYFi8GBb2+EK5pmmjAP2fTmxPDq6p0CI6oIViiQqmRkniR9IvKgb4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
